version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /mock_machina
    schedule:
      interval: weekly
    groups:
      go-deps:
        patterns: ["*"]
