// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../cache.dart';
import '../error.dart';
import '../events.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `store`

void storeOpen({required String path}) =>
    RustLib.instance.api.crateApiStoreStoreOpen(path: path);

bool storeIsOpen() => RustLib.instance.api.crateApiStoreStoreIsOpen();

void storeSet({
  required String key,
  required List<int> value,
  PlatformInt64? ttlMs,
  required bool encrypted,
}) => RustLib.instance.api.crateApiStoreStoreSet(
  key: key,
  value: value,
  ttlMs: ttlMs,
  encrypted: encrypted,
);

Uint8List? storeGet({required String key}) =>
    RustLib.instance.api.crateApiStoreStoreGet(key: key);

bool storeContains({required String key}) =>
    RustLib.instance.api.crateApiStoreStoreContains(key: key);

bool storeDelete({required String key}) =>
    RustLib.instance.api.crateApiStoreStoreDelete(key: key);

void storeClear() => RustLib.instance.api.crateApiStoreStoreClear();

List<String> storeKeys() => RustLib.instance.api.crateApiStoreStoreKeys();

PlatformInt64 storeLen() => RustLib.instance.api.crateApiStoreStoreLen();

Map<String, Entry> storeGetAll() =>
    RustLib.instance.api.crateApiStoreStoreGetAll();

void storeSetEncryptionKey({required List<int> key}) =>
    RustLib.instance.api.crateApiStoreStoreSetEncryptionKey(key: key);

Uint8List storeGenerateEncryptionKey() =>
    RustLib.instance.api.crateApiStoreStoreGenerateEncryptionKey();

PlatformInt64 storeIncrement({
  required String key,
  required PlatformInt64 delta,
  PlatformInt64? ttlMs,
}) => RustLib.instance.api.crateApiStoreStoreIncrement(
  key: key,
  delta: delta,
  ttlMs: ttlMs,
);

bool storeSetIfAbsent({
  required String key,
  required List<int> value,
  PlatformInt64? ttlMs,
  required bool encrypted,
}) => RustLib.instance.api.crateApiStoreStoreSetIfAbsent(
  key: key,
  value: value,
  ttlMs: ttlMs,
  encrypted: encrypted,
);

PlatformInt64 storePurgeExpired() =>
    RustLib.instance.api.crateApiStoreStorePurgeExpired();

void storeCompact() => RustLib.instance.api.crateApiStoreStoreCompact();

Stream<StorageEvent> storeWatch({required String pattern}) =>
    RustLib.instance.api.crateApiStoreStoreWatch(pattern: pattern);
