// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Entry {
  final Uint8List value;
  final bool encrypted;
  final BigInt? expiresAt;

  const Entry({required this.value, required this.encrypted, this.expiresAt});

  @override
  int get hashCode => value.hashCode ^ encrypted.hashCode ^ expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Entry &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          encrypted == other.encrypted &&
          expiresAt == other.expiresAt;
}
