// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class StoreError with _$StoreError implements FrbException {
  const StoreError._();

  const factory StoreError.notInitialized() = StoreError_NotInitialized;
  const factory StoreError.alreadyInitialized() = StoreError_AlreadyInitialized;
  const factory StoreError.io(String field0) = StoreError_Io;
  const factory StoreError.serialization(String field0) =
      StoreError_Serialization;
  const factory StoreError.encryptionKeyNotSet() =
      StoreError_EncryptionKeyNotSet;
  const factory StoreError.invalidKeyLength(BigInt field0) =
      StoreError_InvalidKeyLength;
  const factory StoreError.encryption() = StoreError_Encryption;
  const factory StoreError.invalidCiphertext() = StoreError_InvalidCiphertext;
  const factory StoreError.unsupportedEncryptionVersion(int field0) =
      StoreError_UnsupportedEncryptionVersion;
  const factory StoreError.authenticationFailed() =
      StoreError_AuthenticationFailed;
  const factory StoreError.invalidCounterValue(String field0) =
      StoreError_InvalidCounterValue;
}
