// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'events.freezed.dart';

@freezed
sealed class StorageEvent with _$StorageEvent {
  const StorageEvent._();

  const factory StorageEvent.keyCreated({required String key}) =
      StorageEvent_KeyCreated;
  const factory StorageEvent.keyUpdated({required String key}) =
      StorageEvent_KeyUpdated;
  const factory StorageEvent.keyDeleted({required String key}) =
      StorageEvent_KeyDeleted;
  const factory StorageEvent.keyExpired({required String key}) =
      StorageEvent_KeyExpired;
  const factory StorageEvent.storageCleared() = StorageEvent_StorageCleared;
  const factory StorageEvent.cacheInvalidated({required String key}) =
      StorageEvent_CacheInvalidated;
}
