// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/store.dart';
import 'cache.dart';
import 'dart:async';
import 'dart:convert';
import 'error.dart';
import 'events.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiStoreInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1132064374;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rodinia_ffi',
        ioDirectory: '../rodinia_ffi/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiStoreInitApp();

  void crateApiStoreStoreClear();

  void crateApiStoreStoreCompact();

  bool crateApiStoreStoreContains({required String key});

  bool crateApiStoreStoreDelete({required String key});

  Uint8List crateApiStoreStoreGenerateEncryptionKey();

  Uint8List? crateApiStoreStoreGet({required String key});

  Map<String, Entry> crateApiStoreStoreGetAll();

  PlatformInt64 crateApiStoreStoreIncrement({
    required String key,
    required PlatformInt64 delta,
    PlatformInt64? ttlMs,
  });

  bool crateApiStoreStoreIsOpen();

  List<String> crateApiStoreStoreKeys();

  PlatformInt64 crateApiStoreStoreLen();

  void crateApiStoreStoreOpen({required String path});

  PlatformInt64 crateApiStoreStorePurgeExpired();

  void crateApiStoreStoreSet({
    required String key,
    required List<int> value,
    PlatformInt64? ttlMs,
    required bool encrypted,
  });

  void crateApiStoreStoreSetEncryptionKey({required List<int> key});

  bool crateApiStoreStoreSetIfAbsent({
    required String key,
    required List<int> value,
    PlatformInt64? ttlMs,
    required bool encrypted,
  });

  Stream<StorageEvent> crateApiStoreStoreWatch({required String pattern});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiStoreInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStoreInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  void crateApiStoreStoreClear() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_store_error,
        ),
        constMeta: kCrateApiStoreStoreClearConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreStoreClearConstMeta =>
      const TaskConstMeta(debugName: "store_clear", argNames: []);

  @override
  void crateApiStoreStoreCompact() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_store_error,
        ),
        constMeta: kCrateApiStoreStoreCompactConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreStoreCompactConstMeta =>
      const TaskConstMeta(debugName: "store_compact", argNames: []);

  @override
  bool crateApiStoreStoreContains({required String key}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_store_error,
        ),
        constMeta: kCrateApiStoreStoreContainsConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreStoreContainsConstMeta =>
      const TaskConstMeta(debugName: "store_contains", argNames: ["key"]);

  @override
  bool crateApiStoreStoreDelete({required String key}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_store_error,
        ),
        constMeta: kCrateApiStoreStoreDeleteConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreStoreDeleteConstMeta =>
      const TaskConstMeta(debugName: "store_delete", argNames: ["key"]);

  @override
  Uint8List crateApiStoreStoreGenerateEncryptionKey() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStoreStoreGenerateEncryptionKeyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreStoreGenerateEncryptionKeyConstMeta =>
      const TaskConstMeta(
        debugName: "store_generate_encryption_key",
        argNames: [],
      );

  @override
  Uint8List? crateApiStoreStoreGet({required String key}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_store_error,
        ),
        constMeta: kCrateApiStoreStoreGetConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreStoreGetConstMeta =>
      const TaskConstMeta(debugName: "store_get", argNames: ["key"]);

  @override
  Map<String, Entry> crateApiStoreStoreGetAll() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_Map_String_entry_None,
          decodeErrorData: sse_decode_store_error,
        ),
        constMeta: kCrateApiStoreStoreGetAllConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreStoreGetAllConstMeta =>
      const TaskConstMeta(debugName: "store_get_all", argNames: []);

  @override
  PlatformInt64 crateApiStoreStoreIncrement({
    required String key,
    required PlatformInt64 delta,
    PlatformInt64? ttlMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          sse_encode_i_64(delta, serializer);
          sse_encode_opt_box_autoadd_i_64(ttlMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_store_error,
        ),
        constMeta: kCrateApiStoreStoreIncrementConstMeta,
        argValues: [key, delta, ttlMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreStoreIncrementConstMeta =>
      const TaskConstMeta(
        debugName: "store_increment",
        argNames: ["key", "delta", "ttlMs"],
      );

  @override
  bool crateApiStoreStoreIsOpen() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStoreStoreIsOpenConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreStoreIsOpenConstMeta =>
      const TaskConstMeta(debugName: "store_is_open", argNames: []);

  @override
  List<String> crateApiStoreStoreKeys() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_store_error,
        ),
        constMeta: kCrateApiStoreStoreKeysConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreStoreKeysConstMeta =>
      const TaskConstMeta(debugName: "store_keys", argNames: []);

  @override
  PlatformInt64 crateApiStoreStoreLen() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_store_error,
        ),
        constMeta: kCrateApiStoreStoreLenConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreStoreLenConstMeta =>
      const TaskConstMeta(debugName: "store_len", argNames: []);

  @override
  void crateApiStoreStoreOpen({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_store_error,
        ),
        constMeta: kCrateApiStoreStoreOpenConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreStoreOpenConstMeta =>
      const TaskConstMeta(debugName: "store_open", argNames: ["path"]);

  @override
  PlatformInt64 crateApiStoreStorePurgeExpired() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_store_error,
        ),
        constMeta: kCrateApiStoreStorePurgeExpiredConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreStorePurgeExpiredConstMeta =>
      const TaskConstMeta(debugName: "store_purge_expired", argNames: []);

  @override
  void crateApiStoreStoreSet({
    required String key,
    required List<int> value,
    PlatformInt64? ttlMs,
    required bool encrypted,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          sse_encode_list_prim_u_8_loose(value, serializer);
          sse_encode_opt_box_autoadd_i_64(ttlMs, serializer);
          sse_encode_bool(encrypted, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_store_error,
        ),
        constMeta: kCrateApiStoreStoreSetConstMeta,
        argValues: [key, value, ttlMs, encrypted],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreStoreSetConstMeta => const TaskConstMeta(
    debugName: "store_set",
    argNames: ["key", "value", "ttlMs", "encrypted"],
  );

  @override
  void crateApiStoreStoreSetEncryptionKey({required List<int> key}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_store_error,
        ),
        constMeta: kCrateApiStoreStoreSetEncryptionKeyConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreStoreSetEncryptionKeyConstMeta =>
      const TaskConstMeta(
        debugName: "store_set_encryption_key",
        argNames: ["key"],
      );

  @override
  bool crateApiStoreStoreSetIfAbsent({
    required String key,
    required List<int> value,
    PlatformInt64? ttlMs,
    required bool encrypted,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          sse_encode_list_prim_u_8_loose(value, serializer);
          sse_encode_opt_box_autoadd_i_64(ttlMs, serializer);
          sse_encode_bool(encrypted, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_store_error,
        ),
        constMeta: kCrateApiStoreStoreSetIfAbsentConstMeta,
        argValues: [key, value, ttlMs, encrypted],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreStoreSetIfAbsentConstMeta =>
      const TaskConstMeta(
        debugName: "store_set_if_absent",
        argNames: ["key", "value", "ttlMs", "encrypted"],
      );

  @override
  Stream<StorageEvent> crateApiStoreStoreWatch({required String pattern}) {
    final sink = RustStreamSink<StorageEvent>();
    handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pattern, serializer);
          sse_encode_StreamSink_storage_event_Sse(sink, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_store_error,
        ),
        constMeta: kCrateApiStoreStoreWatchConstMeta,
        argValues: [pattern, sink],
        apiImpl: this,
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiStoreStoreWatchConstMeta => const TaskConstMeta(
    debugName: "store_watch",
    argNames: ["pattern", "sink"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Map<String, Entry> dco_decode_Map_String_entry_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_entry(raw).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  RustStreamSink<StorageEvent> dco_decode_StreamSink_storage_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  Entry dco_decode_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Entry(
      value: dco_decode_list_prim_u_8_strict(arr[0]),
      encrypted: dco_decode_bool(arr[1]),
      expiresAt: dco_decode_opt_box_autoadd_u_64(arr[2]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, Entry)> dco_decode_list_record_string_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_entry).toList();
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  (String, Entry) dco_decode_record_string_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_entry(arr[1]));
  }

  @protected
  StorageEvent dco_decode_storage_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return StorageEvent_KeyCreated(key: dco_decode_String(raw[1]));
      case 1:
        return StorageEvent_KeyUpdated(key: dco_decode_String(raw[1]));
      case 2:
        return StorageEvent_KeyDeleted(key: dco_decode_String(raw[1]));
      case 3:
        return StorageEvent_KeyExpired(key: dco_decode_String(raw[1]));
      case 4:
        return StorageEvent_StorageCleared();
      case 5:
        return StorageEvent_CacheInvalidated(key: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  StoreError dco_decode_store_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return StoreError_NotInitialized();
      case 1:
        return StoreError_AlreadyInitialized();
      case 2:
        return StoreError_Io(dco_decode_String(raw[1]));
      case 3:
        return StoreError_Serialization(dco_decode_String(raw[1]));
      case 4:
        return StoreError_EncryptionKeyNotSet();
      case 5:
        return StoreError_InvalidKeyLength(dco_decode_usize(raw[1]));
      case 6:
        return StoreError_Encryption();
      case 7:
        return StoreError_InvalidCiphertext();
      case 8:
        return StoreError_UnsupportedEncryptionVersion(dco_decode_u_8(raw[1]));
      case 9:
        return StoreError_AuthenticationFailed();
      case 10:
        return StoreError_InvalidCounterValue(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Map<String, Entry> sse_decode_Map_String_entry_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_entry(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  RustStreamSink<StorageEvent> sse_decode_StreamSink_storage_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  Entry sse_decode_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_value = sse_decode_list_prim_u_8_strict(deserializer);
    var var_encrypted = sse_decode_bool(deserializer);
    var var_expiresAt = sse_decode_opt_box_autoadd_u_64(deserializer);
    return Entry(
      value: var_value,
      encrypted: var_encrypted,
      expiresAt: var_expiresAt,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, Entry)> sse_decode_list_record_string_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, Entry)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_entry(deserializer));
    }
    return ans_;
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, Entry) sse_decode_record_string_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_entry(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  StorageEvent sse_decode_storage_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_key = sse_decode_String(deserializer);
        return StorageEvent_KeyCreated(key: var_key);
      case 1:
        var var_key = sse_decode_String(deserializer);
        return StorageEvent_KeyUpdated(key: var_key);
      case 2:
        var var_key = sse_decode_String(deserializer);
        return StorageEvent_KeyDeleted(key: var_key);
      case 3:
        var var_key = sse_decode_String(deserializer);
        return StorageEvent_KeyExpired(key: var_key);
      case 4:
        return StorageEvent_StorageCleared();
      case 5:
        var var_key = sse_decode_String(deserializer);
        return StorageEvent_CacheInvalidated(key: var_key);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  StoreError sse_decode_store_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return StoreError_NotInitialized();
      case 1:
        return StoreError_AlreadyInitialized();
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return StoreError_Io(var_field0);
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return StoreError_Serialization(var_field0);
      case 4:
        return StoreError_EncryptionKeyNotSet();
      case 5:
        var var_field0 = sse_decode_usize(deserializer);
        return StoreError_InvalidKeyLength(var_field0);
      case 6:
        return StoreError_Encryption();
      case 7:
        return StoreError_InvalidCiphertext();
      case 8:
        var var_field0 = sse_decode_u_8(deserializer);
        return StoreError_UnsupportedEncryptionVersion(var_field0);
      case 9:
        return StoreError_AuthenticationFailed();
      case 10:
        var var_field0 = sse_decode_String(deserializer);
        return StoreError_InvalidCounterValue(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_Map_String_entry_None(
    Map<String, Entry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_entry(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_storage_event_Sse(
    RustStreamSink<StorageEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_storage_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_entry(Entry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.value, serializer);
    sse_encode_bool(self.encrypted, serializer);
    sse_encode_opt_box_autoadd_u_64(self.expiresAt, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_entry(
    List<(String, Entry)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_entry(
    (String, Entry) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_entry(self.$2, serializer);
  }

  @protected
  void sse_encode_storage_event(StorageEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case StorageEvent_KeyCreated(key: final key):
        sse_encode_i_32(0, serializer);
        sse_encode_String(key, serializer);
      case StorageEvent_KeyUpdated(key: final key):
        sse_encode_i_32(1, serializer);
        sse_encode_String(key, serializer);
      case StorageEvent_KeyDeleted(key: final key):
        sse_encode_i_32(2, serializer);
        sse_encode_String(key, serializer);
      case StorageEvent_KeyExpired(key: final key):
        sse_encode_i_32(3, serializer);
        sse_encode_String(key, serializer);
      case StorageEvent_StorageCleared():
        sse_encode_i_32(4, serializer);
      case StorageEvent_CacheInvalidated(key: final key):
        sse_encode_i_32(5, serializer);
        sse_encode_String(key, serializer);
    }
  }

  @protected
  void sse_encode_store_error(StoreError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case StoreError_NotInitialized():
        sse_encode_i_32(0, serializer);
      case StoreError_AlreadyInitialized():
        sse_encode_i_32(1, serializer);
      case StoreError_Io(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case StoreError_Serialization(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
      case StoreError_EncryptionKeyNotSet():
        sse_encode_i_32(4, serializer);
      case StoreError_InvalidKeyLength(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_usize(field0, serializer);
      case StoreError_Encryption():
        sse_encode_i_32(6, serializer);
      case StoreError_InvalidCiphertext():
        sse_encode_i_32(7, serializer);
      case StoreError_UnsupportedEncryptionVersion(field0: final field0):
        sse_encode_i_32(8, serializer);
        sse_encode_u_8(field0, serializer);
      case StoreError_AuthenticationFailed():
        sse_encode_i_32(9, serializer);
      case StoreError_InvalidCounterValue(field0: final field0):
        sse_encode_i_32(10, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
